language: node_js
node_js:
  - "6"
before_script:
  - npm install mocha
  - npm install codecov
script: mocha Test/test1.js Test/test2.js 
after_success:
  - codecov --token=c186f38f-d474-4350-9419-af731ec7869f