language: python
python:
    - "2.7"
install:
  - pip install codecov
  - pip install coverage
script:
 - python -m unittest discover -v
 - coverage run test.py 
 after_success:
  - codecov --token=c186f38f-d474-4350-9419-af731ec7869f 